name: SCA

on:
  push:
    branches: ["master", "main", "**"]

jobs:
  snyk-cli:
    uses: auth0/devsecops-tooling/.github/workflows/sca-scan.yml@main
    with:
      java-version: "17"
      pre-scan-commands: "./gradlew :guardian:dependencies --no-daemon --console=plain"
      additional-arguments: "--exclude=app"
    secrets: inherit
